version: "3.9"

x-defaults: &defaults
  restart: ${DOCKER_RESTART_POLICY}
  logging:
    driver: "json-file"
    options:
      max-file: "10"
      max-size: "10m"

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK}

services:
  web:
    <<: *defaults
    image: ${NODE_IMAGE}
    container_name: "${APP_ID}-web"
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html/application
    command: pnpm dev:web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=default"
      # --- web (nextjs) ---
      - "traefik.http.services.${APP_ID}-web.loadbalancer.server.port=3000"
      - "traefik.http.routers.${APP_ID}-web.service=${APP_ID}-web"
      - "traefik.http.routers.${APP_ID}-web.rule=HostRegexp(`web.${WEB_HOST}`)"
      - "traefik.http.routers.${APP_ID}-web.entrypoints=https"
      - "traefik.http.routers.${APP_ID}-web.tls=true"
      - "traefik.http.routers.${APP_ID}-web.tls.certresolver=local"
      - "traefik.http.routers.${APP_ID}-web.tls.domains[0].main=web.${WEB_HOST}"
      - "dev.mediafactory.application.runenv=${USE_ENVIRONMENT}"
    user: ${MY_UID}:${MY_GID}
    networks:
      - default
