version: "3.9"

x-defaults: &defaults
  restart: ${DOCKER_RESTART_POLICY}
  logging:
    driver: "json-file"
    options:
      max-file: "10"
      max-size: "10m"

networks:
  default:
    external:
    name: webapp

services:
  nextjs:
    <<: *defaults
    image: ${APP_NODE_IMAGE}
    container_name: "${APP_ID}-nextjs"
    hostname: "${APP_HOSTNAME}-nextjs"
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html/application
    entrypoint: "yarn dev"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=default"
      - "traefik.http.routers.${APP_ID}-secure.rule=HostRegexp(`${APP_HOST}`)"
      - "traefik.http.routers.${APP_ID}-secure.entrypoints=https"
      - "traefik.http.routers.${APP_ID}-secure.tls=true"
      - "traefik.http.routers.${APP_ID}-secure.tls.certresolver=local"
      - "traefik.http.routers.${APP_ID}-secure.tls.domains[0].main=${APP_HOST}"
      - "traefik.http.services.${APP_ID}.loadbalancer.server.port=3000"
      - "dev.mediafactory.application.runenv=${USE_ENVIRONMENT}"
    user: ${MY_UID}:${MY_GID}
    networks:
      - default

  app-storybook:
    <<: *defaults
    image: ${APP_NODE_IMAGE}
    container_name: "${APP_ID}-storybook"
    hostname: "${APP_HOSTNAME}-storybook"
    command: "yarn storybook-react"
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html/application
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=webapp"
      - "traefik.http.routers.${APP_ID}-storybook.rule=Host(`storybook.${APP_HOST}`)"
      - "traefik.http.routers.${APP_ID}-storybook.entrypoints=https"
      - "traefik.http.routers.${APP_ID}-storybook.tls=true"
      - "traefik.http.routers.${APP_ID}-storybook.tls.certresolver=local"
      - "traefik.http.routers.${APP_ID}-storybook.tls.domains[0].main=storybook.${APP_HOST}"
      - "traefik.http.services.${APP_ID}-storybook.loadbalancer.server.port=6006"
    networks:
      - webapp
