version: "3.9"

x-defaults: &defaults
  restart: ${DOCKER_RESTART_POLICY}
  logging:
    driver: "json-file"
    options:
      max-file: "10"
      max-size: "10m"

services:
  nextjs:
    <<: *defaults
    image: ${APP_NODE_IMAGE}
    container_name: "${CONTAINER_NAME_PREFIX}-web"
    hostname: "${APP_HOSTNAME}-web"
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html/application
    entrypoint: "yarn dev"
    labels:
      - "dev.mediafactory.application.runenv=${USE_ENVIRONMENT}"
      - "traefik.enable=true"
      - "traefik.docker.network=webapp"
      - "traefik.http.routers.${CONTAINER_NAME_PREFIX}-secure.rule=HostRegexp(`${APP_HOST}`)"
      - "traefik.http.routers.${CONTAINER_NAME_PREFIX}-secure.entrypoints=https"
      - "traefik.http.routers.${CONTAINER_NAME_PREFIX}-secure.tls=true"
      - "traefik.http.routers.${CONTAINER_NAME_PREFIX}-secure.tls.certresolver=local"
      - "traefik.http.routers.${CONTAINER_NAME_PREFIX}-secure.tls.domains[0].main=${APP_HOST}"
      - "traefik.http.services.${CONTAINER_NAME_PREFIX}.loadbalancer.server.port=8080"
    networks:
      - webapp

  app-storybook:
    <<: *defaults
    image: ${APP_NODE_IMAGE}
    container_name: "${CONTAINER_NAME_PREFIX}-storybook"
    hostname: "${APP_HOSTNAME}-storybook"
    command: "yarn storybook-react"
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html/application
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=webapp"
      - "traefik.http.routers.${CONTAINER_NAME_PREFIX}-storybook.rule=Host(`storybook.${APP_HOST}`)"
      - "traefik.http.routers.${CONTAINER_NAME_PREFIX}-storybook.entrypoints=https"
      - "traefik.http.routers.${CONTAINER_NAME_PREFIX}-storybook.tls=true"
      - "traefik.http.routers.${CONTAINER_NAME_PREFIX}-storybook.tls.certresolver=local"
      - "traefik.http.routers.${CONTAINER_NAME_PREFIX}-storybook.tls.domains[0].main=storybook.${APP_HOST}"
      - "traefik.http.services.${CONTAINER_NAME_PREFIX}-storybook.loadbalancer.server.port=6006"
    networks:
      - webapp
