version: "3.9"

x-defaults: &defaults
  restart: ${DOCKER_RESTART_POLICY}
  logging:
    driver: "json-file"
    options:
      max-file: "10"
      max-size: "10m"

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK}
  intnet:
    external: false
    name: ${APP_ID}-cms-intnet
    driver: bridge

volumes:
  cms-db-data:
    driver: local

services:
  cms:
    <<: *defaults
    image: ${NODE_IMAGE}
    container_name: "${APP_ID}-cms"
    restart: "no"
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: ${CMS_DB_NAME}
      DATABASE_USERNAME: ${CMS_DB_USERNAME}
      DATABASE_PASSWORD: ${CMS_DB_PASSWORD}
      DATABASE_SSL: false
      DOCKER_HOST_MACHINE_IP: ${DOCKER_HOST_MACHINE_IP}
    command: yarn dev
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DOCKER_NETWORK}"
      - "traefik.http.services.${APP_ID}-cms.loadbalancer.server.port=1337"
      - "traefik.http.routers.${APP_ID}-cms.service=${APP_ID}-cms"
      - "traefik.http.routers.${APP_ID}-cms.rule=Host(`cms.${APP_HOST}`)"
      - "traefik.http.routers.${APP_ID}-cms.entrypoints=https"
      - "traefik.http.routers.${APP_ID}-cms.tls=true"
      - "traefik.http.routers.${APP_ID}-cms.tls.certresolver=local"
      - "traefik.http.routers.${APP_ID}-cms.tls.domains[0].main=cms.${APP_HOST}"
    ports:
      - "1337:1337"
    volumes:
      - ./:/var/www/html/
    working_dir: /var/www/html/application/backends/cms
    depends_on:
      - db
    networks:
      - default
      - intnet

  db:
    <<: *defaults
    image: postgres
    container_name: "${APP_ID}-cms-db"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${CMS_DB_PASSWORD}
      POSTGRES_USER: ${CMS_DB_USERNAME}
      POSTGRES_DB: ${CMS_DB_NAME}
    volumes:
      - cms-db-data:/var/lib/postgresql/data
    labels:
      - "traefik.enable=false"
    networks:
      - intnet

  adminer:
    image: adminer
    container_name: "${APP_ID}-cms-adminer"
    environment:
      ADMINER_DEFAULT_SERVER: db
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DOCKER_NETWORK}"
      - "traefik.http.routers.${APP_ID}-adminer.rule=Host(`adminer.cms.${APP_HOST}`)"
      - "traefik.http.routers.${APP_ID}-adminer.entrypoints=https"
      - "traefik.http.routers.${APP_ID}-adminer.tls=true"
      - "traefik.http.routers.${APP_ID}-adminer.tls.certresolver=local"
      - "traefik.http.routers.${APP_ID}-adminer.tls.domains[0].main=adminer.cms.${APP_HOST}"
    networks:
      - default
      - intnet
    depends_on:
      - db
